# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vehicledetectionmessage.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dvehicledetectionmessage.proto\x12\x10vehicledetection\"f\n\tPBMessage\x12\x0e\n\x06source\x18\x01 \x01(\r\x12\x0e\n\x06target\x18\x02 \x01(\r\x12.\n\x07\x63ontrol\x18\x03 \x01(\x0b\x32\x1b.vehicledetection.PBControlH\x00\x42\t\n\x07msgtype\"5\n\tPBControl\x12(\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x18.vehicledetection.Action*\x19\n\x06\x41\x63tion\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x62\x06proto3')

_ACTION = DESCRIPTOR.enum_types_by_name['Action']
Action = enum_type_wrapper.EnumTypeWrapper(_ACTION)
OFF = 0
ON = 1


_PBMESSAGE = DESCRIPTOR.message_types_by_name['PBMessage']
_PBCONTROL = DESCRIPTOR.message_types_by_name['PBControl']
PBMessage = _reflection.GeneratedProtocolMessageType('PBMessage', (_message.Message,), {
  'DESCRIPTOR' : _PBMESSAGE,
  '__module__' : 'vehicledetectionmessage_pb2'
  # @@protoc_insertion_point(class_scope:vehicledetection.PBMessage)
  })
_sym_db.RegisterMessage(PBMessage)

PBControl = _reflection.GeneratedProtocolMessageType('PBControl', (_message.Message,), {
  'DESCRIPTOR' : _PBCONTROL,
  '__module__' : 'vehicledetectionmessage_pb2'
  # @@protoc_insertion_point(class_scope:vehicledetection.PBControl)
  })
_sym_db.RegisterMessage(PBControl)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTION._serialized_start=210
  _ACTION._serialized_end=235
  _PBMESSAGE._serialized_start=51
  _PBMESSAGE._serialized_end=153
  _PBCONTROL._serialized_start=155
  _PBCONTROL._serialized_end=208
# @@protoc_insertion_point(module_scope)
